# Generated by Django 3.2 on 2021-04-24 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=240)),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=2)),
                ('area_code', models.CharField(max_length=2)),
                ('number', models.CharField(max_length=10)),
                ('type', models.CharField(choices=[('W', 'Work'), ('P', 'Cellphone'), ('R', 'Residential')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('id_card', models.CharField(max_length=20)),
                ('social_security_number', models.CharField(max_length=11, unique=True)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('F', 'Fluid'), ('P', 'Person')], max_length=10)),
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.email')),
                ('phones', models.ManyToManyField(to='api.Phone')),
            ],
        ),
    ]
