version: "3.9"
services:
  clients_api:
    container_name: clients_api
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /opt/clients/
    command: bash -c "python manage.py runserver 0:80"
    env_file:
      - .env
    expose:
      - "80"
    networks:
      clients:
        ipv4_address: 172.16.239.10
    volumes:
      - ./clients:/opt/clients/
      - ./clients/my.cnf:/etc/my.cnf
    depends_on:
      - clients_database

  clients_database:
    container_name: clients_database
    image: "mysql:5.7"
    expose:
      - "3306"
      - "33060"
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', "--max-connections=500"]
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: clients
    networks:
      clients:
        ipv4_address: 172.16.239.11

networks:
  clients:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.239.0/24
          gateway: 172.16.239.1